// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmsatrgxukszdyhbgaei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtc2F0cmd4dWtzemR5aGJnYWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDgwMzksImV4cCI6MjA3NTM4NDAzOX0.Cj6R7ua4zo2Gko1f3MiHyDoNiWXmvksSla67yzDFtqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});